import asyncio
import os
from motor.motor_asyncio import AsyncIOMotorClient
from passlib.context import CryptContext
from dotenv import load_dotenv
import logging

# Load environment
load_dotenv("backend/.env")

MONGO_URI = os.getenv("MONGO_URL")
DB_NAME = os.getenv("DB_NAME", "clinicflow")

# Match server.py context
PWD_SCHEME = os.environ.get('PASSWORD_SCHEME', 'bcrypt')
if PWD_SCHEME == 'sha256_crypt':
    pwd_context = CryptContext(schemes=['sha256_crypt', 'bcrypt'], deprecated="auto")
else:
    pwd_context = CryptContext(schemes=['bcrypt', 'sha256_crypt'], deprecated="auto")

async def debug_login():
    print(f"Connecting to {DB_NAME}...")
    client = AsyncIOMotorClient(MONGO_URI)
    db = client[DB_NAME]
    
    email = "admin@clinicflow.com"
    password_attempt = "admin@123"
    
    user = await db.users.find_one({"email": email})
    
    if not user:
        print(f"❌ User {email} NOT FOUND in database!")
    else:
        print(f"✅ User found: {user.get('name')} (ID: {user.get('id')})")
        stored_hash = user.get('password_hash')
        print(f"   Stored Hash (start): {stored_hash[:20]}...")
        
        # Verify
        is_valid = pwd_context.verify(password_attempt, stored_hash)
        if is_valid:
            print(f"✅ Password '{password_attempt}' MATCHES the stored hash!")
        else:
            print(f"❌ Password '{password_attempt}' DOES NOT match the stored hash.")
            
            # Debug: Generate new hash and show it
            new_hash = pwd_context.hash(password_attempt)
            print(f"   If we hashed '{password_attempt}' now, it would look like: {new_hash[:20]}...")
            
            # Force update just in case
            print("   ⚠️  Forcing update with new hash generated by THIS script context...")
            await db.users.update_one(
                {"email": email},
                {"$set": {"password_hash": new_hash}}
            )
            print("   ✅ Force update complete. Try logging in again.")

if __name__ == "__main__":
    asyncio.run(debug_login())
